# Generated by Django 5.0.6 on 2024-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_task_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
