# Generated by Django 5.0.6 on 2024-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_task_options_remove_task_position_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('C', 'Completada')], default='Pendiente', help_text='Estado de la tarea (Pendiente o Completada)', max_length=1),
        ),
    ]
