# Generated by Django 5.0.6 on 2024-05-28 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Valor unico por tarea', primary_key=True, serialize=False, unique=True),
        ),
    ]
